In [96]:
import numpy as np 

In [97]:
ar1 = np.random.random((4,6))
print(ar1)
print("shape:",ar1.shape,"size:", ar1.size, "ndim", ar1.ndim, "dtype", ar1.dtype)

[[0.95719465 0.25267067 0.66071202 0.78053798 0.13657888 0.41622424]
 [0.08135293 0.38101231 0.53382317 0.11149851 0.44714237 0.02631364]
 [0.65630009 0.41656122 0.30418161 0.37733768 0.1703147  0.62780349]
 [0.18634239 0.00962979 0.91140036 0.79225984 0.93008427 0.1928731 ]]
shape: (4, 6) size: 24 ndim 2 dtype float64


In [98]:
ar2 = ar1.reshape((3,8))
print(ar2)
print(ar1.size)
ar3 = ar1.reshape(ar1.size) # 转置为一维
print(ar3)
ar3 = ar1.reshape(-1) # 转置为一维
print(ar3)

[[0.95719465 0.25267067 0.66071202 0.78053798 0.13657888 0.41622424
  0.08135293 0.38101231]
 [0.53382317 0.11149851 0.44714237 0.02631364 0.65630009 0.41656122
  0.30418161 0.37733768]
 [0.1703147  0.62780349 0.18634239 0.00962979 0.91140036 0.79225984
  0.93008427 0.1928731 ]]
24
[0.95719465 0.25267067 0.66071202 0.78053798 0.13657888 0.41622424
 0.08135293 0.38101231 0.53382317 0.11149851 0.44714237 0.02631364
 0.65630009 0.41656122 0.30418161 0.37733768 0.1703147  0.62780349
 0.18634239 0.00962979 0.91140036 0.79225984 0.93008427 0.1928731 ]
[0.95719465 0.25267067 0.66071202 0.78053798 0.13657888 0.41622424
 0.08135293 0.38101231 0.53382317 0.11149851 0.44714237 0.02631364
 0.65630009 0.41656122 0.30418161 0.37733768 0.1703147  0.62780349
 0.18634239 0.00962979 0.91140036 0.79225984 0.93008427 0.1928731 ]


In [102]:
ar3_1 = np.random.randint(0,10, (4,4))
ar3_2 = np.random.randint(0,10, (4,4))
print(ar3_1, "\n", ar3_2)
ar3_3 = np.hstack([ar3_1, ar3_2])
print(ar3_3)
ar3_4 = np.vstack([ar3_1, ar3_2])
print(ar3_4)

[[4 4 6 7]
 [7 6 3 6]
 [3 8 1 9]
 [4 2 0 1]] 
 [[7 4 2 9]
 [1 2 4 2]
 [8 0 6 4]
 [3 6 9 3]]
[[4 4 6 7 7 4 2 9]
 [7 6 3 6 1 2 4 2]
 [3 8 1 9 8 0 6 4]
 [4 2 0 1 3 6 9 3]]
[[4 4 6 7]
 [7 6 3 6]
 [3 8 1 9]
 [4 2 0 1]
 [7 4 2 9]
 [1 2 4 2]
 [8 0 6 4]
 [3 6 9 3]]


In [100]:
ar4 = np.zeros((16,16))
# ar4[1:1][1:-1] = 0 # 不可以用这种方式
ar4[0] = 1
ar4[:, 0] = 1
ar4[-1] = 1
ar4[:, -1] = 1
print(ar4)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [167]:
ar5 = np.random.randint(0, 100, 100)
# print(ar5)
print("avg:", np.mean(ar5), "方差", ar5.var(), "标准差", ar5.std())
print("min:", ar5.min(), "max:", ar5.max(), "mi", ar5.max() - ar5.min())
ar5_1 = (ar5 - ar5.mean())/ar5.std()
print(ar5_1)
print(ar5 == ar5.max())
ar5_2 = np.argwhere(ar5 == ar5.max()) # 定位用
print(ar5_2)
print("max", ar5.max(), ar5.argmax())
ar5_3 = np.argwhere(ar5 == ar5.min()) # 定位用
print(ar5_3)
print("min", ar5.min(), ar5.argmin())
ar5_4 = (ar5- ar5.min())/(ar5.max()-ar5.min())
print(ar5_4)

avg: 46.34 方差 831.2244000000001 标准差 28.83096252295438
min: 1 max: 99 mi 98
[ 0.19631672  1.6530839   0.05757699 -0.982971   -0.53206687 -0.25458741
 -1.53792992  1.6530839  -0.982971    0.50848112  1.09812498 -0.25458741
  0.71659071 -0.53206687  1.61839897 -0.94828606  1.41028937 -0.42801207
 -1.01765593 -0.84423127 -0.94828606 -1.01765593  1.13280991  1.41028937
 -1.05234086  1.34091951 -0.15053261  0.68190578 -0.15053261  1.82650857
  1.82650857  0.16163179  0.89001538 -1.57261486 -1.53792992 -0.80954633
  0.12694685  1.23686471  0.78596058 -1.22576553 -1.29513539 -0.39332714
 -1.57261486  0.64722085 -0.60143674  1.68776883 -0.94828606  1.58371404
  1.09812498  1.13280991  0.92470031  1.16749484  0.12694685  0.33505645
 -0.982971   -0.8789162  -0.63612167  1.37560444  0.75127565 -1.05234086
 -0.32395727 -1.50324499 -0.94828606 -0.84423127  0.75127565  1.23686471
  0.43911125  0.85533044 -0.6708066  -0.04647781 -0.32395727 -0.60143674
  0.43911125 -0.21990247 -0.39332714 -0.01179288 

In [170]:
x6 = np.random.randint(80, 100, 30)
print(x6)
x6_1 = x6[x6 >= 95]
print(x6_1)
x6_2 = x6[x6 <= 95]
print(x6_2)
# tmp = 85 < x6 
# tmp2 = x6 < 95
# tmp3 = tmp * tmp2
# print(tmp)
# print(tmp2)
# print(tmp3)
x6_3 = x6[(85 < x6) * (x6 < 95)] # 取并集
print(x6_3)
x6_4 = np.sort(x6)
print(x6_4)

[94 86 98 81 91 90 93 93 89 85 98 82 90 85 95 99 83 84 97 98 97 84 91 95
 90 80 90 94 81 84]
[98 98 95 99 97 98 97 95]
[94 86 81 91 90 93 93 89 85 82 90 85 95 83 84 84 91 95 90 80 90 94 81 84]
[94 86 91 90 93 93 89 90 91 90 90 94]
[80 81 81 82 83 84 84 84 85 85 86 89 90 90 90 90 91 91 93 93 94 94 95 95
 97 97 98 98 98 99]


In [195]:
# A = np.random.randint(1, 10, (3,3))
# B = np.random.randint(1, 10, (3,3))

A = np.array([[5,7,5],[7,1,7],[6,6,8]])
B = np.array([[9,5,1],[2,6,6],[9,2,9]])
print(A,"\n", B)
import time
import timeit

[[5 7 5]
 [7 1 7]
 [6 6 8]] 
 [[9 5 1]
 [2 6 6]
 [9 2 9]]


In [207]:
def py_dot(_A, _B) :
    _tmp = np.empty((3,3))
    for i in range(len(_A)) :
        for j in range(len(_B)) :
            _tmp[i][j] = _A[i][j] * _B[i][j]
        # _tmp.append(_tmp2)
    return _tmp
            
%timeit py_dot(A, B)
tmp = py_dot(A, B)
print(tmp)
%timeit (A * B)
tmp = (A * B)
print(tmp)
            

9.23 µs ± 291 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[[45. 35.  5.]
 [14.  6. 42.]
 [54. 12. 72.]]
428 ns ± 12 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[[45 35  5]
 [14  6 42]
 [54 12 72]]
