In [19]:
import numpy as np 

In [23]:
ar1 = np.random.random((4,6))
print(ar1)
print("shape:",ar1.shape,"size:", ar1.size, "ndim", ar1.ndim, "dtype", ar1.dtype)

[[0.03252069 0.08623074 0.05354644 0.47104932 0.86503734 0.21194538]
 [0.95574501 0.22781794 0.9788125  0.64047461 0.186261   0.19915367]
 [0.96201639 0.79423244 0.77300142 0.18038486 0.88661811 0.76627759]
 [0.72781156 0.97059611 0.14660037 0.3845751  0.52774053 0.79284952]]
shape: (4, 6) size: 24 ndim 2 dtype float64


In [35]:
ar2 = ar1.reshape((3,8))
print(ar2)
print(ar1.size)
ar3 = ar1.reshape(ar1.size) # 转置为一维
print(ar3)
ar3 = ar1.reshape(-1) # 转置为一维
print(ar3)

[[0.03252069 0.08623074 0.05354644 0.47104932 0.86503734 0.21194538
  0.95574501 0.22781794]
 [0.9788125  0.64047461 0.186261   0.19915367 0.96201639 0.79423244
  0.77300142 0.18038486]
 [0.88661811 0.76627759 0.72781156 0.97059611 0.14660037 0.3845751
  0.52774053 0.79284952]]
24
[0.03252069 0.08623074 0.05354644 0.47104932 0.86503734 0.21194538
 0.95574501 0.22781794 0.9788125  0.64047461 0.186261   0.19915367
 0.96201639 0.79423244 0.77300142 0.18038486 0.88661811 0.76627759
 0.72781156 0.97059611 0.14660037 0.3845751  0.52774053 0.79284952]
[0.03252069 0.08623074 0.05354644 0.47104932 0.86503734 0.21194538
 0.95574501 0.22781794 0.9788125  0.64047461 0.186261   0.19915367
 0.96201639 0.79423244 0.77300142 0.18038486 0.88661811 0.76627759
 0.72781156 0.97059611 0.14660037 0.3845751  0.52774053 0.79284952]


In [39]:
ar3_1 = np.random.randint(0,10, (4,4))
ar3_2 = np.random.randint(0,10, (4,4))
print(ar3_1, "\n", ar3_2)
ar3_3 = np.hstack([ar3_1, ar3_2])
print(ar3_3)
ar3_4 = np.vstack([ar3_1, ar3_2])
print(ar3_4)

[[8 3 2 7]
 [2 9 0 7]
 [7 5 9 2]
 [9 6 9 2]] 
 [[9 6 2 8]
 [3 3 8 3]
 [3 2 4 6]
 [3 6 7 7]]
[[8 3 2 7 9 6 2 8]
 [2 9 0 7 3 3 8 3]
 [7 5 9 2 3 2 4 6]
 [9 6 9 2 3 6 7 7]]
[[8 3 2 7]
 [2 9 0 7]
 [7 5 9 2]
 [9 6 9 2]
 [9 6 2 8]
 [3 3 8 3]
 [3 2 4 6]
 [3 6 7 7]]


In [86]:
ar4 = np.zeros((16,16))
# ar4[1:1][1:-1] = 0 # 不可以用这种方式
ar4[0] = 1
ar4[:, 0] = 1
ar4[-1] = 1
ar4[:, -1] = 1
print(ar4)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [89]:
ar5 = np.random.randint(0, 100, 10000)
print("avg:", np.average(ar5), "normal")

avg: 49.6944 normal
