In [63]:
import numpy as np

实现两个矩阵的乘法

In [100]:
def multi(a, b):
    # 它只有在第一个矩阵的列数（column）和第二个矩阵的行数（row）相同时才有意义
    a_row = len(a[0]) # p
    a_col = len(a) #  m
    b_row = len(b[0]) # n
    b_col = len(b) # p
    if a_row != b_col:
        print( '输入了非同型矩阵', a_row, b_col)
        return
    else:
        ## 构建目标矩阵形状 构建全0矩阵
        ## 这种写法导致复制出相同的[0,0]
        # matrix = [[0] * a_col] * b_row
        matrix = [[0] * a_col for i in range(b_row) ] # 采用列表推导形式生成
        print(id(matrix[0]))
        print(id(matrix[1]))
        # 横竖错位相乘累加
        for i in range(a_col):
            for j in range(b_row):
                # print(matrix)
                # print("--------")
                for k in range(b_col):
                    matrix[i][j] += a[i][k] * b[k][j]
        return matrix

In [103]:
if __name__ == '__main__':
    a1 = [[1,2]
        ,[2,3]]
    b1 = [[1,0]
        ,[2,1]]
    c1 = multi(a1,b1)
    print(c1)
    print("============================")
    a2 = np.array(a1)
    b2 = np.array(b1)
    print(a2,"\n",b2)

    c2 = a2 * b2
    print("*=\n",c2)
    c2 = np.dot(a2,b2)
    print("dot=\n",c2)
    print("end")


2341209236936
2341215835528
[[5, 2], [8, 3]]
[[1 2]
 [2 3]] 
 [[1 0]
 [2 1]]
*=
 [[1 0]
 [4 3]]
dot=
 [[5 2]
 [8 3]]
end
